# .github/ISSUE_TEMPLATE/bug_report.yml

name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Please describe the problem you encountered.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |-
        List the steps to make the bug happen, for example:
        1. Go to the homepage
        2. Click on the login button
        3. Enter your credentials
        4. See the error message
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect to happen instead?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop, or paste screenshots here if they help explain the issue.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any other information that might help us understand or fix the issue.
